"""Initial migration with upvote_count and Upvote table

Revision ID: efd84bb26ab4
Revises: 
Create Date: 2024-11-25 18:09:47.264127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efd84bb26ab4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=64), nullable=False),
    sa.Column('locations', sa.String(length=120), nullable=False),
    sa.Column('job_title', sa.String(length=64), nullable=False),
    sa.Column('job_description', sa.String(length=120), nullable=False),
    sa.Column('hourly_pay', sa.Integer(), nullable=False),
    sa.Column('benefits', sa.String(length=120), nullable=False),
    sa.Column('review', sa.String(length=120), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('recommendation', sa.Integer(), nullable=False),
    sa.Column('upvote_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_benefits'), 'reviews', ['benefits'], unique=False)
    op.create_index(op.f('ix_reviews_department'), 'reviews', ['department'], unique=False)
    op.create_index(op.f('ix_reviews_job_description'), 'reviews', ['job_description'], unique=False)
    op.create_index(op.f('ix_reviews_job_title'), 'reviews', ['job_title'], unique=False)
    op.create_index(op.f('ix_reviews_locations'), 'reviews', ['locations'], unique=False)
    op.create_index(op.f('ix_reviews_review'), 'reviews', ['review'], unique=False)
    op.create_table('users',
    sa.Column('user_name', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=24), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('user_name')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_password'), 'users', ['password'], unique=False)
    op.create_index(op.f('ix_users_type'), 'users', ['type'], unique=False)
    op.create_table('jobs',
    sa.Column('job_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=164), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=164), nullable=False),
    sa.Column('pay', sa.Float(), nullable=True),
    sa.Column('posted_date', sa.DateTime(), nullable=True),
    sa.Column('employer_id', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['users.user_name'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_jobs_title'), 'jobs', ['title'], unique=False)
    op.create_table('upvote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.ForeignKeyConstraint(['user_name'], ['users.user_name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id', 'user_name', name='_review_user_uc')
    )
    op.create_table('applications',
    sa.Column('application_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=10), nullable=False),
    sa.Column('application_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.ForeignKeyConstraint(['user_name'], ['users.user_name'], ),
    sa.PrimaryKeyConstraint('application_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applications')
    op.drop_table('upvote')
    op.drop_index(op.f('ix_jobs_title'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_users_type'), table_name='users')
    op.drop_index(op.f('ix_users_password'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_reviews_review'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_locations'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_job_title'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_job_description'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_department'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_benefits'), table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
